#!/data/data/com.termux/files/usr/bin/sh
set -e -u

show_help() {
	echo 'Software Installer'
	echo ''
	echo 'A Tool Help You Complier Softwares'
	echo ''
	echo '  install <packages>'
	echo '  list'
	exit 1
}

if [ $# = 0 ]; then show_help; fi
CMD="$1"
shift 1

case "$CMD" in
	h*) show_help;;
	i*) bash -c "$(curl -fsSL https://raw.githubusercontent.com/YadominJinta/TermuxStore-Src/master/config/$@/config.sh)"&&echo ;;
	list) bash -c "$(curl -fsSL https://raw.githubusercontent.com/YadominJinta/TermuxStore-Src/master/config/list/config.sh)" ;;
	*) echo "Unknown command: '$CMD' (run 'sft help' for usage information)";;
esac

